In [2]:
import numpy as np

In [15]:
a11 = [[1,2],[5,6]]
b11 = [[1,2],[12,9]]
a12 = [[3],[7]]
b21 = [[10,11]]
b12 = [[3],[5]]
b22 = [[12]]

In [16]:
np.dot(a11,b11)+np.dot(a12,b21)

array([[ 55,  53],
       [147, 141]])

In [25]:
np.dot(a11,b12) + np.dot(a12,b22)

array([[ 49],
       [129]])

In [24]:
 np.dot(a12,b22)

array([[36],
       [84]])

In [31]:
A = [[1,2,3],[5,6,7],[9,12,13],[10,11,12]]
B = [[1,2,3],[12,9,5],[10,11,12]]

In [32]:
np.dot(A,B)

array([[ 55,  53,  49],
       [147, 141, 129],
       [283, 269, 243],
       [262, 251, 229]])

In [33]:
# Checking Bock Multiplication

In [34]:
a11 = [[1,2],[5,6]]
a12 = [[3],[7]]
a21 = [[9,12],[10,11]]
a22 = [[13],[12]]

b11 = [[1,2],[12,9]]
b12 = [[3],[5]]
b21 = [[10,11]]
b22 = [[12]]

In [44]:
A = [[a11,a12],[a21,a22]]
B = [[b11,b12],[b21,b22]]

In [45]:
A

[[[[1, 2], [5, 6]], [[3], [7]]], [[[9, 12], [10, 11]], [[13], [12]]]]

In [46]:
B

[[[[1, 2], [12, 9]], [[3], [5]]], [[[10, 11]], [[12]]]]

In [24]:
x = "hello"

#if condition returns False, AssertionError is raised:
assert x == "goodbye", "x should be 'hello'"

AssertionError: x should be 'hello'

In [12]:
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [2]:
import numpy as np

In [10]:
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,23])
print(data.shape)
for i in data:
    print(i)

(11,)
0
1
2
3
4
5
6
7
8
9
23


In [28]:
np.maximum(4,6)

6

In [29]:
Z = np.array([1, 3, -1, -4, -5, 7, 9, 18]).reshape(4,2)

In [30]:
Z

array([[ 1,  3],
       [-1, -4],
       [-5,  7],
       [ 9, 18]])

In [38]:
np.maximum(2, [0,1])

array([2, 2])

In [39]:
Z = np.array([[11,19,10], [12, 21, 23]])

In [40]:
Z

array([[11, 19, 10],
       [12, 21, 23]])

In [41]:
Z_exp = np.exp(Z)

In [42]:
Z_exp

array([[5.98741417e+04, 1.78482301e+08, 2.20264658e+04],
       [1.62754791e+05, 1.31881573e+09, 9.74480345e+09]])

In [47]:
np.sum(Z_exp,axis = 0, keepdims = True)

array([[2.22628933e+05, 1.49729804e+09, 9.74482547e+09]])

In [44]:
Z_exp.shape

(2, 3)

In [45]:
np.sum(Z_exp,axis = 0, keepdims = True).shape

(1, 3)

In [49]:
np.random.seed(2)

In [50]:
dimensions = [784, 3, 7, 10]

In [56]:
np.random.randn(dimensions[1], dimensions[1-1]) * 0.1

array([[ 0.06650944, -0.19626047,  0.2112715 , ..., -0.05681802,
         0.01129414, -0.0368358 ],
       [ 0.00601845, -0.03105775,  0.14861889, ...,  0.14708598,
         0.03016764,  0.12239688],
       [-0.03950099, -0.03477958,  0.02362006, ...,  0.09956872,
         0.09214558, -0.09948918]])

In [57]:
H_prev = np.array([[1,0, 5, 10, 2], [2, 5, 3, 10, 2]])
W_sample = np.array([[10, 5], [2, 0], [1, 0]])
b_sample = np.array([10, 5, 0]).reshape((3, 1))

In [59]:
np.dot(W_sample,H_prev)

array([[ 20,  25,  65, 150,  30],
       [  2,   0,  10,  20,   4],
       [  1,   0,   5,  10,   2]])

In [60]:
np.dot(W_sample,H_prev)+b_sample

array([[ 30,  35,  75, 160,  40],
       [  7,   5,  15,  25,   9],
       [  1,   0,   5,  10,   2]])

In [62]:
params = {'w1':[1,2,3,4],'w2':[4,4,5,6]}

In [64]:
len(params)

2

In [66]:
x_sample = train_set_x[:, 10:20]
print(x_sample.shape)

NameError: name 'train_set_x' is not defined

In [82]:
p1 = np.array([[0.10106734,0.10567625,0.09824287,0.10028288,0.09883601,0.10668575,0.09832513,0.09747092,0.09489069,0.09852217],[0.10106734,0.10567625,0.09824287,0.10028288,0.09883601,0.10668575,0.09832513,0.09747092,0.09489069,0.09852217]])

In [103]:
y = np.array([[0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,1,0]])

In [104]:
x = p1.T
y = y.T

In [105]:
p3 = x[:,0]
y3 = y[:,0]

In [106]:
y3

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [93]:
np.sum(x, axis=0)

array([1.00000001, 1.00000001])

In [95]:
np.log(x[:,0])

array([-2.29196825, -2.2473751 , -2.3203126 , -2.29976029, -2.31429327,
       -2.23786768, -2.31947564, -2.3282012 , -2.35502968, -2.31747368])

In [100]:
1./m*np.sum(np.multiply(4,-np.log(x[:,0])))

46.063514786518176

In [ ]:
log_likelihood = -np.log(p[range(m),y])
loss = np.sum(log_likelihood) / m

In [107]:
1./2*np.sum(np.multiply(y3,-np.log(p3)))

1.1189338408041445

In [108]:
loss = np.squeeze(1./2*np.sum(np.multiply(y3,-np.log(p3))))

In [109]:
loss

1.1189338408041445

In [2]:
for l in reversed(range(4)):
    print(l)

3
2
1
0
